### ISSUE TITLE
Update README with Reveal.js commands

### ISSUE THREAD

**Issue by pichfl** [mainmatter/svelte-workshop#6]
We should document how to open Presenter notes etc.

**Comment by marcoow** [comment]
also first clone:

```
~/Code/svelte-workshop[main] » pnpm serve
 WARN  Unsupported engine: wanted: {"node":">=18.0.0"} (current: {"node":"v14.15.1","pnpm":"7.14.2"})

> Mainmatter SvelteKit Workshop: Workshop Slides@0.0.0 serve /Users/marcoow/Code/svelte-workshop
> vite preview

error when starting preview server:
Error: The directory "dist" does not exist. Did you build your project?
    at preview (file:///Users/marcoow/Code/svelte-workshop/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65641:15)
    at async CAC.<anonymous> (file:///Users/marcoow/Code/svelte-workshop/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/cli.js:896:24)
 ELIFECYCLE  Command failed with exit code 1.
```

once it runs:
